selected_scheme scheme-basic
binary_x86_64-linux 1
collection-binextra 1
collection-bibtexextra 1
collection-latex 1
collection-latexrecommended 1
collection-latexextra 1
collection-luatex 1
collection-metapost 1
collection-pictures 1
collection-plaingeneric 1
collection-langeuropean 1
instopt_adjustpath 1
