FROM maclotsen/texlive:latest

WORKDIR /tmp/google-fonts

# Download & install fonts
RUN wget -q https://github.com/google/fonts/archive/main.tar.gz && \
    tar -xzf main.tar.gz && \
    mv fonts-main /usr/share/fonts && \
    rm -rf /tmp/google-fonts

# Reload the font db again
RUN fc-cache -fv && \
    luaotfload-tool --update

# Restore to LaTeX context
WORKDIR /build
