name: Build LaTeX Document

on:
  push:
    branches:
      - '*'
    paths:
      - action.yml
  pull_request:
    types: [opened, synchronize]
    paths:
      - action.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4
        with:
          path: xdp-docker
      - name: Check out test package
        uses: actions/checkout@v4
        with:
          repository: Xerdi/gitinfo-lua
          path: gitinfo-lua
          fetch-tags: true
          fetch-depth: 0
      - name: Check out texmf (branding)
        uses: actions/checkout@v4
        with:
          repository: Xerdi/texmf-packaging
          path: texmf
      - name: Run the build process with Custom Docker Action
        uses: ./xdp-docker/action.yml
        with:
          command: "make -C gitinfo-lua manual"
